version: "2.1"
services:
  collectd:
    build: collectd
    volumes:
      - ./collectd/collectd.conf:/etc/collectd/collectd.conf
      - ./log:/var/log
    networks:
      - sensor
    links:
      - redis
    depends_on:
      - redis 

  collectd_script:
    build: collectd_script
    volumes:
      - ./collectd_script:/collectd_script
    networks:
      - sensor
    links:
      - redis
    depends_on:
      - redis 

  redis:
    build: redis
    volumes:
      - ./redis/redis.conf:/etc/redis.conf
      - ./log:/var/log
    expose:
      - "6379" 
    networks:
      sensor:
        ipv4_address: 172.20.0.10
        aliases:
          - redis    

networks:
  sensor:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
